### ISSUE TITLE
Fees data

### ISSUE THREAD

**Issue by roma219** [bitshares/vuex-bitshares#60]
Fees data for placing/cancelling order is required for a market, both in base and quote amounts.

**Comment by youaresofunny** [comment]
How it could work:
- getOrderSides (market service) will also return market commissions (like 5% or so in open. assets)
(so this method will be renamed to getMarketDataForOrder)
- createOrder will combine it with transaction commission and provide valid order for placing & separated comissions object (will be also renamed into generateOrder)
- placeOrder will do same job as now

**Comment by roma219** [comment]
@youaresofunny Is there any way to know the comissions before creating order sides etc? As we need to know what is the max amount user can spend for order ( userAssetBalance - comissions )

**Comment by youaresofunny** [comment]
Hm, so it's a way to add market.getCommissions(quote_id) that will return actual commissions.
But the key is that market commissions are deduced from placed order.

As for transaction commissions - there are universal mechanism to get em all, it is in parameters service now.

**Comment by youaresofunny** [comment]
https://github.com/bitshares/vuex-bitshares/pull/63
https://github.com/bitshares/bitshares-community-ui/pull/280
