### ISSUE TITLE
dev branch

### ISSUE THREAD

**Issue by roma219** [bitshares/vuex-bitshares#7]
Let's have it as a main development branch. Still need to figure out how to deal with PRs in UI repo that require separate branch in this repo...

@youaresofunny

**Comment by youaresofunny** [comment]
Will see on first UI PR that will use separate Vuex branch.

**Comment by roma219** [comment]
@youaresofunny seems to be working :) http://staging-ui.trusty.apasia.tech:8080/44-basic-login
